#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: classpath:cert/give928-keystore.p12
#    key-store-type: PKCS12
#    key-store-password: 123456
#    enabled-protocols: TLSv1.2,TLSv1.3
#  http2:
#    enabled: true

spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:pool:postgres://127.0.0.1:5432/subway
    username: subway
    password: subway_password
  redis:
    host: 127.0.0.1
    port: 7617
    password: predixy_password
  data:
    redis:
      repositories:
        enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:/db/postgres/migration
    url: jdbc:postgresql://127.0.0.1:5432/subway
    user: subway
    password: subway_password

logging:
  level:
    nextstep.subway: debug
    io.r2dbc.postgresql.QUERY: debug
    io.r2dbc.postgresql.PARAM: debug
    io.r2dbc.pool.ConnectionPool: debug
    org.springframework.r2dbc.connection.R2dbcTransactionManager: debug
    io.lettuce.core.RedisChannelHandler: debug
