#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: classpath:cert/give928-keystore.p12
#    key-store-type: PKCS12
#    key-store-password: 123456
#    enabled-protocols: TLSv1.2,TLSv1.3
#  http2:
#    enabled: true

spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    driver: pool
    protocol: mysql
    host: localhost
    port: 3306
    username: subway
    password: subway_password
    database: subway
    connection-timeout: 10s
    ssl: false
    poolName: master-pool
    initial-size: 10
    max-size: 30
    max-idle-time: 15s
    max-life-time: 30s
    max-create-connection-time: 3s
    max-acquire-time: 4s
    acquire-retry: 1
    validation-query: select 1
    register-jmx: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:/db/migration

logging:
  level:
    org.springframework.r2dbc.core.DefaultDatabaseClient: debug
    nextstep.subway: debug
