spring:
  profiles:
    active: local
  webflux:
    static-path-pattern: "/**"
  web:
    resources:
      static-locations: "classpath:/static/"
  data:
    rest:
      default-media-type: application/json
      default-page-size: 10
      max-page-size: 100

server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 512

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000
