version: '2.1'

services:
  mysql-master:
    image: docker.io/bitnami/mysql:8.0
    container_name: mysql-master
    ports:
      - '3306:3306'
    volumes:
      - './data:/bitnami/mysql/data'
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_DATABASE=subway
      - MYSQL_USER=subway
      - MYSQL_PASSWORD=subway_password
      - MYSQL_ROOT_PASSWORD=root_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mysql-slave:
    image: docker.io/bitnami/mysql:8.0
    container_name: mysql-slave
    ports:
      - '3307:3306'
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_DATABASE=subway
      - MYSQL_USER=subway
      - MYSQL_PASSWORD=subway_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=root_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
