version: '2'

services:
  postgresql-master:
    image: bitnami/postgresql:latest
    container_name: postgresql-master
    ports:
      - '5432:5432'
    volumes:
      - './data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_DATABASE=subway
      - POSTGRESQL_USERNAME=subway
      - POSTGRESQL_PASSWORD=subway_password
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1

  postgresql-slave:
    image: bitnami/postgresql:latest
    container_name: postgresql-slave
    ports:
      - '5433:5432'
    depends_on:
      - mysql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PASSWORD=subway_password
