version: '2'

# redis-cli --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 --cluster-replicas 1 --cluster-yes

services:
  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    container_name: redis-node-1
    hostname: redis-node-1
    volumes:
      - ./redis-cluster-data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis_password'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
      - 'REDIS_DISABLE_COMMANDS=KEYS,FLUSHALL,FLUSHDB'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    container_name: redis-node-2
    hostname: redis-node-2
    volumes:
      - ./redis-cluster-data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis_password'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
      - 'REDIS_DISABLE_COMMANDS=KEYS,FLUSHALL,FLUSHDB'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.0
    container_name: redis-node-3
    hostname: redis-node-3
    volumes:
      - ./redis-cluster-data-3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis_password'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
      - 'REDIS_DISABLE_COMMANDS=KEYS,FLUSHALL,FLUSHDB'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.0
    container_name: redis-node-4
    hostname: redis-node-4
    volumes:
      - ./redis-cluster-data-4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis_password'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
      - 'REDIS_DISABLE_COMMANDS=KEYS,FLUSHALL,FLUSHDB'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.0
    container_name: redis-node-5
    hostname: redis-node-5
    volumes:
      - ./redis-cluster-data-5:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis_password'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
      - 'REDIS_DISABLE_COMMANDS=KEYS,FLUSHALL,FLUSHDB'

  redis-node-6:
    image: docker.io/bitnami/redis-cluster:7.0
    container_name: redis-node-6
    hostname: redis-node-6
    volumes:
      - ./redis-cluster-data-6:/bitnami/redis/data
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      - 'REDIS_PASSWORD=redis_password'
      - 'REDISCLI_AUTH=redis_password'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_DISABLE_COMMANDS=KEYS,FLUSHALL,FLUSHDB'

  predixy:
    image: haandol/predixy:latest
    container_name: predixy
    hostname: predixy
    ports:
      - "7617:7617"
    volumes:
      - ./predixy/conf:/etc/predixy/conf
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
